### PR TITLE
feat(es_extended2/common/functions): added logs documentation and little optimizations

### PR DESCRIPTION
**Pull request by Konijntje-x**
Also changed the names of esx 1 and esx 2.

### CODE REVIEW

**Comment by ESXCrackhead** [comment]
title: ES Extended Legacy docs - ESX Legacy Docs
title: ES Extended Reborn docs - ESX Reborn Docs

**Comment by ESXCrackhead** [comment]
Additionally, there is no "esx:logs:toDiscord" event, you should check the events again.

**Comment by Konijntje-x** [comment]
> Additionally, there is no "esx:logs:toDiscord" event, you should check the events again.

so it's just 'logs:toDiscord' @ESXCrackhead ?

**Comment by Konijntje-x** [comment]
fixed

**Pull request closed without merging**
